### PR TITLE
otp: simplify upload flow

### PR DESCRIPTION
**Pull request by dagheyman**
This PR simplifies the recently added upload to YubiCloud feature.

- checkbox moved to next to the finish button, this way the total height of the view doesn't increase.
- drop extra view after finish
- drop showing the generated url in the UI. What was the use case for this? Any known scenarios where `Qt.openUrlExternally(uploadUrl)` doesn't work? Note that if there is no internet access the flow would have failed at an earlier stage, in the preparation.
- some labels and tooltips texts modified

### CODE REVIEW

**Comment by dagheyman** [comment]
NOT READY YET, found some issues.

**Comment by emlun** [comment]
Huh, I've never seen this before, but opening the browser just failed for me:

```
2020-01-10T10:46:00+0100 DEBUG [ykman.descriptor.Descriptor.open_device:86] transports: 0x1, self.mode.transports: 0x7
2020-01-10T10:46:00+0100 DEBUG [ykman.descriptor.open_device:91] Opening driver for serial: None, type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2020-01-10T10:46:00+0100 DEBUG [ykman.descriptor.open_device:94] Attempt 1 of 10
2020-01-10T10:46:00+0100 DEBUG [ykman.driver_otp.open_devices:224] Success in opening key at position 0
2020-01-10T10:46:00+0100 DEBUG [ykman.descriptor.open_device:97] Found driver: <ykman.driver_otp.OTPDriver object at 0x7f9e80feec70>, key_type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2020-01-10T10:46:00+0100 DEBUG [ykman.device.__init__:198] Read config from device...
2020-01-10T10:46:00+0100 DEBUG [ykman.device.__init__:200] Success!
2020-01-10T10:46:00+0100 DEBUG [ykman.device.__init__:289] Identified YubiKey 5
2020-01-10T10:46:01+0100 DEBUG [ykman.driver_otp.close:203] Close <ykman.driver_otp.OTPDriver object at 0x7f9e80feec70>
2020-01-10T10:46:01+0100 DEBUG [ykman.driver_otp.__del__:208] Destroy <ykman.driver_otp.OTPDriver object at 0x7f9e80feec70>
Unable to detect a web browser to launch 'https://upload.yubico.com/proceed/26703f65-b639-4b5d-af7f-be974202419c'
```

second attempt:

```
2020-01-10T10:47:38+0100 DEBUG [ykman.descriptor.Descriptor.open_device:86] transports: 0x1, self.mode.transports: 0x7
2020-01-10T10:47:38+0100 DEBUG [ykman.descriptor.open_device:91] Opening driver for serial: None, type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2020-01-10T10:47:38+0100 DEBUG [ykman.descriptor.open_device:94] Attempt 1 of 10
2020-01-10T10:47:38+0100 DEBUG [ykman.driver_otp.open_devices:224] Success in opening key at position 0
2020-01-10T10:47:38+0100 DEBUG [ykman.descriptor.open_device:97] Found driver: <ykman.driver_otp.OTPDriver object at 0x7f9e80ff9bb0>, key_type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2020-01-10T10:47:38+0100 DEBUG [ykman.device.__init__:198] Read config from device...
2020-01-10T10:47:38+0100 DEBUG [ykman.device.__init__:200] Success!
2020-01-10T10:47:38+0100 DEBUG [ykman.device.__init__:289] Identified YubiKey 5
2020-01-10T10:47:39+0100 DEBUG [ykman.driver_otp.close:203] Close <ykman.driver_otp.OTPDriver object at 0x7f9e80ff9bb0>
2020-01-10T10:47:39+0100 DEBUG [ykman.driver_otp.__del__:208] Destroy <ykman.driver_otp.OTPDriver object at 0x7f9e80ff9bb0>
/usr/bin/xdg-open: line 444: grep: No such file or directory
/usr/bin/xdg-open: line 444: echo: write error: Broken pipe
/usr/bin/xdg-open: line 561: grep: No such file or directory
/usr/bin/xdg-open: line 562: egrep: No such file or directory
/usr/bin/xdg-open: line 574: grep: No such file or directory
xdg-open: file 'https://upload.yubico.com/proceed/1fc9ec31-0247-4af3-87da-a68fa73eace5' does not exist
```

This happens upon clicking the "Finish" button. The toast "Configured Yubico OTP credential. Preparing upload in browser." is shown, but the browser does not open. In 20 repeated attempts, 7 of them successfully opened the browser and 13 failed as above. In 20 repeated attempts on master (d7c745408f845c96151a2f90a1e1327f5593da7a), all 20 succeeded. This is in Sway on Arch Linux, with Firefox set as default browser.

**Comment by dagheyman** [comment]
> I guess we can ask the same question there - why are we showing it in CLI? Any particular reason?

The CLI could be running on an external machine without GUI access, so in that sense I think i makes sense to print the URL.

**Comment by emlun** [comment]
The main reason for showing the URL is that it's a good fallback in case the browser fails to open for some reason. We hadn't actually seen it fail ([until now](https://github.com/Yubico/yubikey-manager-qt/pull/226#issuecomment-572967690)), but I figured it's never good UX to just fail and leave the user with no clear option for how to proceed.

**Pull request merged**
