### PR TITLE
Import PIV Manager functionality

### PR DESCRIPTION
**Pull request by emlun**
Not included:

- Integrations with Microsoft Windows
- Integrations with Mac operating systems

So, how best to review this? :smile:

### CODE REVIEW

**Comment by dagheyman** [comment]
Not sure if it would make things easier, but could we brake out some stuff to a separate PR? I'm thinking of the TouchYourYubikey component and the timer functionality. It would allow to merge that earlier, and it's needed in the ctap2 branch as well.

**Comment by emlun** [comment]
Yeah, sure. Should I break things out into separate branches (rebase etc), then?

**Comment by dagheyman** [comment]
> Should I break things out into separate branches (rebase etc), then?

Yes please.

**Comment by emlun** [comment]
#34 replaces this.

**Pull request closed without merging**
