### PR TITLE
Drop unused PIN/touch policy support code

### PR DESCRIPTION
**Pull request by emlun**

### CODE REVIEW

**Comment by EatonZ** [comment]
@emlun @dagheyman Why was this feature removed from the GUI exactly?

**Comment by emlun** [comment]
@EatonZ This PR did not remove any feature from the GUI, it only removed unused code. If you explore the code in the commit here, you'll see that there is only one call to the changed `piv_generate_certificate` function, and that call does not specify any of the two deleted parameters.

The PIN policy and touch policy features are still available in [the CLI](https://github.com/Yubico/yubikey-manager).

**Comment by EatonZ** [comment]
@emlun I do see it in the CLI, but not the GUI. Is it in the GUI somewhere still?

**Comment by emlun** [comment]
No, it looks like it never was in the GUI. There are some unfinished prototypes in the version history, but they were discarded during the UI redesign for 1.0 and never released.

**Pull request merged**
